; %lpc %s
(__print (char->integer #\A))
(__print (integer->char 97))
(__print (char=? #\a #\a #\a))
(__print (char=? #\a #\b))
(__print (char<? #\a #\b #\c))
(__print (char<? #\a #\c #\b))
(__print (char>? #\c #\b #\a))
(__print (char<=? #\a #\a #\b))
(__print (char>=? #\b #\a #\a))
(__print (char-upcase #\a))
(__print (char-upcase #\1))
(__print (char-downcase #\Z))
(__print (char-ci=? #\a #\A))
(__print (char-ci<? #\A #\b))
(__print (char-ci>? #\b #\A))
(__print (char-ci<=? #\a #\A))
(__print (char-ci>=? #\A #\a))
(__print (char-alphabetic? #\x))
(__print (char-alphabetic? #\1))
(__print (char-numeric? #\5))
(__print (char-numeric? #\x))
(__print (char-whitespace? #\space))
(__print (char-whitespace? #\newline))
(__print (char-whitespace? #\x))
(__print (char-upper-case? #\Q))
(__print (char-lower-case? #\q))
(__print (char-lower-case? #\Q))
