; %lpc %s
(define (make-counter)
  (let ((n 0))
    (lambda () (set! n (+ n 1)) n)))
(define c1 (make-counter))
(define c2 (make-counter))
(define (adder x) (lambda (y) (+ x y)))
(define add5 (adder 5))
(define add10 (adder 10))
(define (even? n) (if (= n 0) #t (odd? (- n 1))))
(define (odd? n) (if (= n 0) #f (even? (- n 1))))
(define (compose f g) (lambda (x) (f (g x))))
(define inc-add5 (compose (lambda (x) (+ x 1)) add5))
(define (vsum . xs) (if (null? xs) 0 (+ (car xs) (apply vsum (cdr xs)))))
(define (make-account balance)
  (lambda (op amount)
    (if (eq? op 'withdraw)
        (begin (set! balance (- balance amount)) balance)
        (begin (set! balance (+ balance amount)) balance))))
(define acc (make-account 100))
(__print (c1))
(__print (c1))
(__print (c2))
(__print (add5 10))
(__print (add10 10))
(__print (even? 10))
(__print (odd? 7))
(__print (inc-add5 1))
(__print (vsum 1 2 3 4 5))
(__print (acc 'withdraw 30))
(__print (acc 'deposit 5))
(__print (map (adder 1) '(1 2 3)))
(__print (procedure? add5))
(__print (vector? add5))
