; %lpc %s
(display "no quotes")
(newline)
(write "with \"quotes\" and \\backslash")
(newline)
(write '(1 "two" #\c (3 . 4)))
(newline)
(display '(1 "two" #\c (3 . 4)))
(newline)
(write #\space)
(write #\newline)
(write #\a)
(newline)
(display #\z)
(newline)
(write '#(1 "s" #\x))
(newline)
(display '#(1 "s" #\x))
(newline)
(write 'sym)
(newline)
(write 42)
(newline)
(write #t)
(newline)
(write '())
(newline)
