; %lpc %s
(define sc (string-copy "abc"))
(define sf (make-string 3 #\a))
(define sal (string #\1 #\2))
(define sal2 sal)

(__print (string #\h #\i))
(__print (make-string 3 #\x))
(__print (make-string 2))
(__print (string-length "hello"))
(__print (string-ref "abc" 1))
(__print (string=? "abc" "abc"))
(__print (string=? "abc" "abd"))
(__print (string<? "abc" "abd"))
(__print (string<? "ab" "abc"))
(__print (string>? "b" "a"))
(__print (string<=? "a" "a" "b"))
(__print (string>=? "b" "a" "a"))
(__print (string-ci=? "Hello" "hELLo"))
(__print (string-ci<? "abc" "ABD"))
(__print (string-ci>? "B" "a"))
(__print (substring "hello" 1 3))
(__print (substring "hello" 0 5))
(__print (string-append "a" "b" "c"))
(__print (string-append))
(__print (string-append "only"))
(__print (string->list "ab"))
(__print (string->list ""))
(__print (list->string '(#\x #\y)))
(__print (list->string '()))
(string-set! sc 0 #\z)
(__print sc)
(string-fill! sf #\b)
(__print sf)
(string-set! sal 1 #\x)
(__print sal2)
(__print (string? "a"))
(__print (string? 'a))
