; %lpc --print expand %s
(lambda (1) 2)
(lambda 1 2)
(set! 1 2)
(define 1 2)
(define () 2)
(define (1) 2)
(define-syntax 1 (syntax-rules () ((_ ) 1)))
(define-syntax x 1)
(define-syntax x (y))
(define-syntax x (syntax-rules 1))
(define-syntax x (syntax-rules (1) ((x) 2)))
(define-syntax x (syntax-rules () (1 2)))
(let-syntax (1) 2)
(let-syntax ((1 (syntax-rules () ((_ ) 2)))) 3)
(let-syntax ((x 1)) 2)
(let ((y 1)) (define-syntax foo (syntax-rules () ((_) 1))) (foo))
(let-syntax ((x)) 1)
(let-syntax ((x (syntax-rules () ((_) 1)))))
(let-syntax ())
(let-syntax 1 2)
