; %lpc %s
(write '(a . b))
(newline)
(write '(a b . c))
(newline)
(write '(a . (b . ())))
(newline)
(write '(a . ()))
(newline)
(display (car '(a . b)))
(newline)
(display (cdr '(a . b)))
(newline)
(display (pair? '(a . b)))
(newline)
(display (pair? '(a b)))
(newline)
